AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs18.x
    Architectures:
      - arm64
    Timeout: 3
    Tracing: Active
    Environment:
      Variables:
        LINE_ACCESS_TOKEN: '{{resolve:secretsmanager:lineAccessToken:SecretString}}'
        LINE_USER_ID: '{{resolve:secretsmanager:lineUserId:SecretString}}'
  Api:
    TracingEnabled: true

Resources:
  WatcherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handler/
      Handler: app.lambdaHandler
      Events:
        DailyWatcherSchedule:
          Type: Schedule
          Properties:
            # Schedule: rate(5 minutes) # For debug
            Schedule: cron(0 1 * * ? *)  # Invoke every day at 10AM JST
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

  LineAccessTokenSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: lineAccessToken
      Description: Secret for LINE Access Token
      SecretString: "dummy-value"

  LineUserIdSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: lineUserId
      Description: Secret for LINE User ID
      SecretString: "dummy-value"
